# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Test actions

on: 
  workflow_dispatch:
    inputs:
      mvn_command:
        description: 'Maven command'     
        required: true
        default: 'clean compile'
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      password:
        description: 'Some password' 
        required: true
        default: 'Some password'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    #Java setup
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 11 
    # Cache maven dependencies
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
              ${{ runner.os }}-maven-  
    # Step that runs the tests
    - name: Build with Maven
      run: echo "::add-mask::${{github.event.inputs.password}}"
